#!/usr/bin/env python

import sys
import ctypes
import ctypes.util

class PamHandle(ctypes.Structure):
    """wrapper class for pam_handle_t pointer"""
    _fields_ = [ ("handle", ctypes.c_void_p) ]

    def __init__(self):
        ctypes.Structure.__init__(self)
        self.handle = 0

class PamMessage(ctypes.Structure):
    """wrapper class for pam_message structure"""
    _fields_ = [ ("msg_style", ctypes.c_int), ("msg", ctypes.c_char_p) ]

    def __repr__(self):
        return "<PamMessage %i '%s'>" % (self.msg_style, self.msg)

class PamResponse(ctypes.Structure):
    """wrapper class for pam_response structure"""
    _fields_ = [ ("resp", ctypes.c_char_p), ("resp_retcode", ctypes.c_int) ]

    def __repr__(self):
        return "<PamResponse %i '%s'>" % (self.resp_retcode, self.resp)

conv_func = ctypes.CFUNCTYPE(ctypes.c_int, ctypes.c_int, ctypes.POINTER(ctypes.POINTER(PamMessage)), ctypes.POINTER(ctypes.POINTER(PamResponse)), ctypes.c_void_p)

class PamConv(ctypes.Structure):
    """wrapper class for pam_conv structure"""
    _fields_ = [ ("conv", conv_func), ("appdata_ptr", ctypes.c_void_p) ]

# Various constants
PAM_PROMPT_ECHO_OFF       = 1
PAM_PROMPT_ECHO_ON        = 2
PAM_ERROR_MSG             = 3
PAM_TEXT_INFO             = 4
PAM_REINITIALIZE_CRED     = 8

libc                      = ctypes.CDLL(ctypes.util.find_library("c"))
libpam                    = ctypes.CDLL(ctypes.util.find_library("pam"))

calloc                    = libc.calloc
calloc.restype            = ctypes.c_void_p
calloc.argtypes           = [ctypes.c_size_t, ctypes.c_size_t]

pam_end                   = libpam.pam_end
pam_end.restype           = ctypes.c_int
pam_end.argtypes          = [PamHandle, ctypes.c_int]

pam_start                 = libpam.pam_start
pam_start.restype         = ctypes.c_int
pam_start.argtypes        = [ctypes.c_char_p, ctypes.c_char_p, ctypes.POINTER(PamConv), ctypes.POINTER(PamHandle)]

pam_setcred               = libpam.pam_setcred
pam_setcred.restype       = ctypes.c_int
pam_setcred.argtypes      = [PamHandle, ctypes.c_int]

pam_strerror              = libpam.pam_strerror
pam_strerror.restype      = ctypes.c_char_p
pam_strerror.argtypes     = [PamHandle, ctypes.c_int]

pam_authenticate          = libpam.pam_authenticate
pam_authenticate.restype  = ctypes.c_int
pam_authenticate.argtypes = [PamHandle, ctypes.c_int]

class pam():
    code   = 0
    reason = None

    def __init__(self):
        pass

    def authenticate(self, username, password, service='login', encoding='utf-8', resetcreds=True):
        """username and password authentication for the given service.

           Returns True for success, or False for failure.

           self.code (integer) and self.reason (string) are always stored and may
           be referenced for the reason why authentication failed. 0/'Success' will
           be stored for success.

           Python3 expects bytes() for ctypes inputs.  This function will make
           necessary conversions using the supplied encoding.

        Inputs:
          username: username to authenticate
          password: password in plain text
          service:  PAM service to authenticate against, defaults to 'login'

        Returns:
          success:  True
          failure:  False
        """

        @conv_func
        def my_conv(n_messages, messages, p_response, app_data):
            """Simple conversation function that responds to any
               prompt where the echo is off with the supplied password"""
            # Create an array of n_messages response objects
            addr = calloc(n_messages, ctypes.sizeof(PamResponse))
            response = ctypes.cast(addr, ctypes.POINTER(PamResponse))
            p_response[0] = response
            for i in range(n_messages):
                if messages[i].contents.msg_style == PAM_PROMPT_ECHO_OFF:
                    dst = calloc(len(password)+1, ctypes.sizeof(ctypes.c_char))
                    ctypes.memmove(dst, cpassword, len(password))
                    response[i].resp = dst
                    response[i].resp_retcode = 0
            return 0

        # python3 ctypes prefers bytes
        if sys.version_info >= (3,):
            if isinstance(username, str): username = username.encode(encoding)
            if isinstance(password, str): password = password.encode(encoding)
            if isinstance(service, str):  service  = service.encode(encoding)
        else:
            if isinstance(username, unicode):
                username = username.encode(encoding)
            if isinstance(password, unicode):
                password = password.encode(encoding)
            if isinstance(service, unicode):
                service  = service.encode(encoding)

        if b'\x00' in username or b'\x00' in password or b'\x00' in service:
            self.code = 4  # PAM_SYSTEM_ERR in Linux-PAM
            self.reason = 'strings may not contain NUL'
            return False

        # do this up front so we can safely throw an exception if there's
        # anything wrong with it
        cpassword = ctypes.c_char_p(password)

        handle = PamHandle()
        conv   = PamConv(my_conv, 0)
        retval = pam_start(service, username, ctypes.byref(conv), ctypes.byref(handle))

        if retval != 0:
            # This is not an authentication error, something has gone wrong starting up PAM
            self.code   = retval
            self.reason = "pam_start() failed"
            return False

        retval = pam_authenticate(handle, 0)
        auth_success = retval == 0

        if auth_success and resetcreds:
            retval = pam_setcred(handle, PAM_REINITIALIZE_CRED);

        # store information to inform the caller why we failed
        self.code   = retval
        self.reason = pam_strerror(handle, retval)
        if sys.version_info >= (3,):
            self.reason = self.reason.decode(encoding)

        pam_end(handle, retval)

        return auth_success


def authenticate(mode, *args, **kwargs):
    """
    Compatibility function for older versions of python-pam.
    """
    if mode == 'pam':
        p = pam()
        p.authenticate(*args, **kwargs)
        return p.code, p.reason
    else:
        return 127, 'Unknown auth method: {}'.format(mode)


if __name__ == "__main__":
    mode = sys.argv[1] if len(sys.argv) > 1 else 'pam'
    username, password = sys.stdin.read().splitlines()
    code, reason = authenticate(mode, username, password)
    sys.stderr.write(reason)
    sys.exit(code)

